apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-web-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-web-application
  template:
    metadata:
      labels:
        app: restaurant-web-application
    spec:
      containers:
      - name: restaurant-web-app-container
        image: santospardos/sanvalero:restaurant
        imagePullPolicy: Always 
        ports:
          - containerPort: 3000
      imagePullSecrets:
      - name: regcred
      
---

apiVersion: v1
kind: Service
metadata:
  name: restaurant-web-app-service
spec:
  selector:
    app: restaurant-web-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
